#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# tools/dump_ir.sh
#
# Role in BackendRace: reproducible compiler-output inspection.  Dumps the LLVM
# IR produced for the AVX2 backend and the PTX produced for the CUDA backend
# into dumps/, each prefixed with an annotated header telling a reviewer exactly
# what to look for.  Run from the repository root:
#
#     ./tools/dump_ir.sh
# ---------------------------------------------------------------------------
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/dumps"
mkdir -p "${OUT}"

CXX="${CXX:-clang++}"
NVCC="${NVCC:-nvcc}"
ARCH_FLAGS="${ARCH_FLAGS:--O3 -march=native}"
SM="${SM:-sm_86}"

echo "==> BackendRace IR/PTX dumper"
echo "    repo    : ${ROOT}"
echo "    output  : ${OUT}"
echo "    clang++ : ${CXX}"
echo "    nvcc    : ${NVCC}"
echo

# ---------------------------------------------------------------------------
# 1) LLVM IR for the AVX2 backend
# ---------------------------------------------------------------------------
if command -v "${CXX}" >/dev/null 2>&1; then
  echo "==> Emitting LLVM IR for backends/simd_avx2.cpp"
  RAW="${OUT}/simd_avx2.raw.ll"
  FINAL="${OUT}/simd_avx2.ll"

  "${CXX}" -std=c++20 ${ARCH_FLAGS} -mavx2 -mfma \
           -I"${ROOT}" \
           -emit-llvm -S "${ROOT}/backends/simd_avx2.cpp" \
           -o "${RAW}"

  cat > "${FINAL}" <<'HEADER'
; ===========================================================================
; BackendRace -- LLVM IR dump of backends/simd_avx2.cpp
; Generated by tools/dump_ir.sh with: clang++ -O3 -march=native -mavx2 -mfma
;                                     -emit-llvm -S
;
; WHAT TO LOOK FOR
; ----------------
; 1. VECTOR TYPES: the hot loops must be dominated by <32 x i8> values. If you
;    see <8 x i32> or scalar i8 operations in verticalAvx2 / horizontalAvx2 /
;    decayAvx2, a byte operation was widened and 4x of the throughput is gone.
;
; 2. INTRINSIC SURVIVAL: search for
;       @llvm.x86.avx2.pshuf.b          (density LUT -> VSHUF equivalent)
;       @llvm.x86.avx2.pblendvb         (the pair-swap select)
;       icmp sgt <32 x i8>              (the biased density comparison)
;    `pshufb` must NOT have been scalarised; `pblendvb` must appear once per
;    pair-swap, not as a chain of selects.
;
; 3. LOADS/STORES AND ALIGNMENT: in verticalAvx2 every
;       load <32 x i8>, ptr %X, align 32
;    should say `align 32`. An `align 1` there means the aligned-load contract
;    of the tiled layout was broken (tile bases are 1024B aligned, row offsets
;    are multiples of 32, so `align 32` is provable).
;
; 4. LOOP STRUCTURE: the `ly` loop of verticalAvx2 should be fully or partially
;    unrolled (look for repeated load/shuffle/cmp/blend/store groups between
;    branch instructions) and free of any bounds-check branches -- the
;    "copy row" boundary cases are hoisted out to the first/last iteration.
;
; 5. REGISTER PRESSURE PROXY: count distinct live <32 x i8> values inside a loop
;    body. More than ~14 in the horizontal pass means the 16 architectural YMM
;    registers will spill; check the final asm with
;       clang++ -O3 -march=native -mavx2 -S backends/simd_avx2.cpp -o -  | grep -c vmovdqa
;    A sudden jump in `vmovdqu ...(%rsp)` traffic is a spill.
;
; 6. WHAT SHOULD *NOT* BE THERE: calls to memcpy inside the inner loop (the
;    34-byte halo gather should be inlined to two movdqu + two byte loads), and
;    any call to br::passes::*Scalar (that means the AVX2 path was compiled out).
; ===========================================================================
HEADER
  cat "${RAW}" >> "${FINAL}"
  rm -f "${RAW}"
  echo "    wrote ${FINAL}"
else
  echo "!!  ${CXX} not found -- skipping LLVM IR dump"
fi

# ---------------------------------------------------------------------------
# 2) PTX for the CUDA backend
# ---------------------------------------------------------------------------
echo
if command -v "${NVCC}" >/dev/null 2>&1; then
  echo "==> Emitting PTX for backends/cuda_backend.cu (arch=${SM})"
  RAW="${OUT}/cuda_backend.raw.ptx"
  FINAL="${OUT}/cuda_backend.ptx"

  "${NVCC}" -std=c++17 -O3 -arch="${SM}" \
            -DBR_WITH_CUDA=1 \
            -I"${ROOT}" \
            --ptx "${ROOT}/backends/cuda_backend.cu" \
            -o "${RAW}"

  cat > "${FINAL}" <<'HEADER'
// ===========================================================================
// BackendRace -- PTX dump of backends/cuda_backend.cu
// Generated by tools/dump_ir.sh with: nvcc -O3 -arch=sm_86 --ptx
//
// WHAT TO LOOK FOR
// ----------------
// 1. MEMORY COALESCING: inside kVertical the global loads should be
//       ld.global.nc.u8   %rs, [%rd + ...];
//    with the address derived from %tid.x with a stride of 1 byte. Thirty-two
//    consecutive threads therefore touch 32 consecutive bytes = one sector.
//    If you see the address multiplied by anything other than 1 in the %tid.x
//    term, the tiled layout <-> block mapping has drifted and each warp will
//    issue 32 separate transactions instead of 1.
//
// 2. `.nc` / __ldg PATH: `ld.global.nc` means the compiler proved the input is
//    read-only (our __restrict__ const pointers) and routed it through the
//    read-only data cache. Losing `.nc` costs L1 hit rate.
//
// 3. SHARED MEMORY: look for `.shared .align 1 .b8 _ZZ...sh[1088]` (kVertical,
//    34*32) and `[1156]` (the 34x34 passes). If these grow, occupancy drops.
//    Also check that `bar.sync 0;` appears exactly once between the halo fill
//    and the compute loop -- a second barrier in the loop is a bug.
//
// 4. REGISTER ALLOCATION: the header comment block emitted by ptxas
//    (`// .maxntid`, and with `-Xptxas -v`: "Used NN registers") should show
//    <= 32 registers/thread for 100% occupancy at 256 threads/block on sm_86.
//    Re-run with:
//       nvcc -O3 -arch=sm_86 -Xptxas -v -c backends/cuda_backend.cu -o /dev/null
//
// 5. PREDICATION VS BRANCHES: the rule functions (swapVertical /
//    swapHorizontal) should lower to `setp` + `selp` chains, not to
//    `bra` divergence. Any `bra` inside the per-cell body means the warp will
//    serialise on material-dependent control flow.
//
// 6. NO LOCAL MEMORY: `ld.local` / `st.local` must NOT appear. If they do, the
//    16-byte density table in densityBiased() was spilled to local memory and
//    should be turned into arithmetic or a __constant__ array.
// ===========================================================================
HEADER
  cat "${RAW}" >> "${FINAL}"
  rm -f "${RAW}"
  echo "    wrote ${FINAL}"
else
  echo "!!  ${NVCC} not found -- skipping PTX dump (CUDA backend needs an NVIDIA toolchain)"
fi

# ---------------------------------------------------------------------------
# 3) Toy ISA disassembly (bonus: the third 'compiler' in the project)
# ---------------------------------------------------------------------------
echo
echo "==> Reminder: dump the TSA-32 program with"
echo "    ./build/br_bench --dump-isa --width 64 --height 64 > dumps/toy_isa.tsa"
echo
echo "Done. Artefacts in ${OUT}"